<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

    <!-- agregar lo correspondiente a Eto.Forms -->
  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.8.3" />
    <PackageReference Include="Eto.Platform.Gtk" Version="2.8.3" />
  </ItemGroup>

  <ItemGroup>
    <!-- Copia canciones.json junto al ejecutable al compilar -->
    <None Include="canciones.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
